version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      ./wait-for-postgres.sh db
      flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/flaskdb
    depends_on:
      - db

  seed:
    build: .
    depends_on:
      - db
    command: >
      sh -c "./wait-for-postgres.sh && python seed.py"

volumes:
  postgres_data:
