"""Initial migration

Revision ID: fbd9bf3a21ff
Revises: 
Create Date: 2025-05-27 00:00:17.907103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbd9bf3a21ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vitals')
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('patients_name_address'))
        batch_op.drop_index(batch_op.f('patients_search_vector'), postgresql_using='gin')

    op.drop_table('Patients')
    op.drop_table('snomed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snomed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snomedid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('effectivetime', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('conceptid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('languagecode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('typeid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('term', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('casesignificanceid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, term)", persisted=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('snomed_pkey'))
    )
    op.create_table('Patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Patients_pkey'))
    )
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('patients_search_vector'), ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('patients_name_address'), ['name', 'address'], unique=False)

    op.create_table('vitals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('definition', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, (((display)::text || ' '::text) || (code)::text))", persisted=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vitals_pkey'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###
